In [1]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [2]:
# Load Data From CSV File
df = pd.read_csv('../excel/users.csv')
cols_id = list(df.columns)

df.head()

,username,user_id,user_watching,user_completed,user_onhold,user_dropped,user_plantowatch,user_days_spent_watching,gender,location,birth_date,access_rank,join_date,last_online,stats_mean_score,stats_rewatched,stats_episodes
0,karthiga,2255153,3,49,1,0,0,55.31,Female,"Chennai, India",1990-04-29,NaN,2013-03-03,2014-02-04 01:32:00,7.43,0.0,3391.0
1,RedvelvetDaisuki,1897606,61,396,39,0,206,118.07,Female,Manila,1995-01-01,NaN,2012-12-13,1900-05-13 02:47:00,6.78,80.0,7094.0
2,Damonashu,37326,45,195,27,25,59,83.70,Male,"Detroit,Michigan",1991-08-01,NaN,2008-02-13,1900-03-24 12:48:00,6.15,6.0,4936.0
3,bskai,228342,25,414,2,5,11,167.16,Male,"Nayarit, Mexico",1990-12-14,NaN,2009-08-31,2014-05-12 16:35:00,8.27,1.0,10081.0
4,terune_uzumaki,327311,5,5,0,0,0,15.20,Female,"Malaysia, Kuantan",1998-08-24,NaN,2010-05-10,2012-10-18 19:06:00,9.70,6.0,920.0

In [3]:
def random_email():
    begin = ''.join(random.choice(string.ascii_lowercase) for x in range(8))
    return begin + "@gmail.com"
def random_password():
    return ''.join(random.choice(string.ascii_letters) for x in range(8))

In [4]:
# Generating random emails and passwords for user login
import random
import string

emails = []
passwords = []

def email_unique():
    email = random_email()
    if email not in emails:
        return email
    else:
        email_unique()
    
for user in range(len(df)):
    email = email_unique()
    password = random_password()
    emails.append(email)
    passwords.append(password)

print(emails[0:5])

['fzqxkake@gmail.com', 'dslqvwup@gmail.com', 'jabkxxbd@gmail.com', 'owphdkhn@gmail.com', 'elaiggqf@gmail.com']

In [5]:
df['email'] = emails
df['password'] = passwords
df.head()

,username,user_id,user_watching,user_completed,user_onhold,user_dropped,user_plantowatch,user_days_spent_watching,gender,location,birth_date,access_rank,join_date,last_online,stats_mean_score,stats_rewatched,stats_episodes,email,password
0,karthiga,2255153,3,49,1,0,0,55.31,Female,"Chennai, India",1990-04-29,NaN,2013-03-03,2014-02-04 01:32:00,7.43,0.0,3391.0,fzqxkake@gmail.com,EUXmWAAT
1,RedvelvetDaisuki,1897606,61,396,39,0,206,118.07,Female,Manila,1995-01-01,NaN,2012-12-13,1900-05-13 02:47:00,6.78,80.0,7094.0,dslqvwup@gmail.com,XFZhJhDl
2,Damonashu,37326,45,195,27,25,59,83.70,Male,"Detroit,Michigan",1991-08-01,NaN,2008-02-13,1900-03-24 12:48:00,6.15,6.0,4936.0,jabkxxbd@gmail.com,opeWuyfa
3,bskai,228342,25,414,2,5,11,167.16,Male,"Nayarit, Mexico",1990-12-14,NaN,2009-08-31,2014-05-12 16:35:00,8.27,1.0,10081.0,owphdkhn@gmail.com,ZnMRTdZL
4,terune_uzumaki,327311,5,5,0,0,0,15.20,Female,"Malaysia, Kuantan",1998-08-24,NaN,2010-05-10,2012-10-18 19:06:00,9.70,6.0,920.0,elaiggqf@gmail.com,iCYSIqFO

In [6]:
df.rename(columns={'user_id': 'id'}, inplace=True)
df.drop(['user_onhold', 'access_rank', 'last_online'], axis=1, inplace=True)
df.head()

,username,id,user_watching,user_completed,user_dropped,user_plantowatch,user_days_spent_watching,gender,location,birth_date,join_date,stats_mean_score,stats_rewatched,stats_episodes,email,password
0,karthiga,2255153,3,49,0,0,55.31,Female,"Chennai, India",1990-04-29,2013-03-03,7.43,0.0,3391.0,fzqxkake@gmail.com,EUXmWAAT
1,RedvelvetDaisuki,1897606,61,396,0,206,118.07,Female,Manila,1995-01-01,2012-12-13,6.78,80.0,7094.0,dslqvwup@gmail.com,XFZhJhDl
2,Damonashu,37326,45,195,25,59,83.70,Male,"Detroit,Michigan",1991-08-01,2008-02-13,6.15,6.0,4936.0,jabkxxbd@gmail.com,opeWuyfa
3,bskai,228342,25,414,5,11,167.16,Male,"Nayarit, Mexico",1990-12-14,2009-08-31,8.27,1.0,10081.0,owphdkhn@gmail.com,ZnMRTdZL
4,terune_uzumaki,327311,5,5,0,0,15.20,Female,"Malaysia, Kuantan",1998-08-24,2010-05-10,9.70,6.0,920.0,elaiggqf@gmail.com,iCYSIqFO

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116133 entries, 0 to 116132
Data columns (total 16 columns):
username                    116132 non-null object
id                          116133 non-null int64
user_watching               116133 non-null int64
user_completed              116133 non-null int64
user_dropped                116133 non-null int64
user_plantowatch            116133 non-null int64
user_days_spent_watching    116133 non-null float64
gender                      116133 non-null object
location                    116127 non-null object
birth_date                  116133 non-null object
join_date                   116133 non-null object
stats_mean_score            116133 non-null float64
stats_rewatched             116133 non-null float64
stats_episodes              116133 non-null float64
email                       116133 non-null object
password                    116133 non-null object
dtypes: float64(4), int64(5), object(7)
memory usage: 14.2+ MB

In [30]:
df["id"] += 1
df.head()

,username,id,user_watching,user_completed,user_dropped,user_plantowatch,user_days_spent_watching,gender,location,birth_date,join_date,stats_mean_score,stats_rewatched,stats_episodes,email,password
0,karthiga,2255154,3,49,0,0,55.31,Female,"Chennai, India",1990-04-29,2013-03-03,7.43,0.0,3391.0,fzqxkake@gmail.com,EUXmWAAT
1,RedvelvetDaisuki,1897607,61,396,0,206,118.07,Female,Manila,1995-01-01,2012-12-13,6.78,80.0,7094.0,dslqvwup@gmail.com,XFZhJhDl
2,Damonashu,37327,45,195,25,59,83.70,Male,"Detroit,Michigan",1991-08-01,2008-02-13,6.15,6.0,4936.0,jabkxxbd@gmail.com,opeWuyfa
3,bskai,228343,25,414,5,11,167.16,Male,"Nayarit, Mexico",1990-12-14,2009-08-31,8.27,1.0,10081.0,owphdkhn@gmail.com,ZnMRTdZL
4,terune_uzumaki,327312,5,5,0,0,15.20,Female,"Malaysia, Kuantan",1998-08-24,2010-05-10,9.70,6.0,920.0,elaiggqf@gmail.com,iCYSIqFO

In [32]:
df.to_csv('../excel/users_process.csv', header = None, index=False)

In [31]:
df.head(50)

,username,id,user_watching,user_completed,user_dropped,user_plantowatch,user_days_spent_watching,gender,location,birth_date,join_date,stats_mean_score,stats_rewatched,stats_episodes,email,password
0,karthiga,2255154,3,49,0,0,55.31,Female,"Chennai, India",1990-04-29,2013-03-03,7.43,0.0,3391.0,fzqxkake@gmail.com,EUXmWAAT
1,RedvelvetDaisuki,1897607,61,396,0,206,118.07,Female,Manila,1995-01-01,2012-12-13,6.78,80.0,7094.0,dslqvwup@gmail.com,XFZhJhDl
2,Damonashu,37327,45,195,25,59,83.70,Male,"Detroit,Michigan",1991-08-01,2008-02-13,6.15,6.0,4936.0,jabkxxbd@gmail.com,opeWuyfa
3,bskai,228343,25,414,5,11,167.16,Male,"Nayarit, Mexico",1990-12-14,2009-08-31,8.27,1.0,10081.0,owphdkhn@gmail.com,ZnMRTdZL
4,terune_uzumaki,327312,5,5,0,0,15.20,Female,"Malaysia, Kuantan",1998-08-24,2010-05-10,9.70,6.0,920.0,elaiggqf@gmail.com,iCYSIqFO
5,Bas_G,5015095,35,114,20,175,30.81,Male,"Nijmegen, Nederland",1999-10-24,2015-11-26,7.86,0.0,1847.0,lgokoodq@gmail.com,riUYiSWh
6,HimeAria,3129316,2,87,0,28,20.12,Female,Poland,1996-09-26,2013-09-08,8.23,0.0,1314.0,vxwqbjej@gmail.com,SlAJxuCm
7,Skallington,326734,0,3,0,0,4.32,Male,Norberg Sweden,1991-03-15,2010-05-09,10.00,7.0,251.0,irmucdft@gmail.com,tmzOLMSZ
8,Slimak,61678,79,224,3,84,126.17,Male,Poland,1988-02-21,2008-05-18,7.77,2.0,7472.0,qgwhllgg@gmail.com,oGecguHU
9,Elysiun,5927343,7,4,0,4,2.09,Male,Nebraska,1984-11-16,2016-12-25,7.40,0.0,121.0,jreazslf@gmail.com,tGcePECU
10,jimothy000,47168,6,0,0,2,7.71,Male,"England,Manchester",1995-04-25,2008-04-01,9.33,5.0,473.0,bkqtwnqh@gmail.com,wEHyYoZr
11,MistButterfly,2485328,66,3923,0,368,614.96,Female,~ Hungary ~,1992-01-16,2013-04-25,5.49,0.0,39893.0,iltoetzp@gmail.com,YFTNHwNE
12,ProperBritish,253614,6,233,9,62,44.63,Male,United Kingdom,1992-02-20,2009-11-01,8.00,2.0,2652.0,famgomxf@gmail.com,eYgQTqXG
13,kioniel,144050,11,433,2,0,166.24,Male,home,1988-01-16,2009-01-29,7.84,0.0,9893.0,vhwbcufe@gmail.com,hFExlZXg
14,Xinil,2,4,230,89,60,133.32,Male,California,1985-03-04,2004-11-05,7.37,58.0,7920.0,slgpzyyz@gmail.com,bmKZvGTp
15,helenply,2529850,9,184,8,39,41.15,Female,Mexico,1999-08-30,2013-05-06,7.19,1.0,2526.0,nqodiscu@gmail.com,iJPyMlzR
16,hood_rad,4538088,1,314,1,160,80.22,Male,Hamilton Ontario,1997-10-31,2015-04-04,0.00,0.0,4800.0,grkwilgc@gmail.com,xiFnegsR
17,detestedlove311,5310,3,29,2,20,24.58,Female,"Chicago, IL",1989-09-14,2007-06-06,7.73,0.0,1447.0,gjqqdynu@gmail.com,lJUGRmAU
18,ihasabucket,18868,6,146,25,15,63.02,Male,"San Jose, CA",1984-09-08,2007-10-26,7.84,0.0,3758.0,bvamwlal@gmail.com,BSxySdXd
19,xTheFallenx,340874,22,655,3,212,131.89,Male,somewhere really hot,1993-05-29,2010-06-13,8.02,0.0,8508.0,qksjylpi@gmail.com,mWMaZVZD
20,L-LawlietDN,14659,5,0,1,0,3.65,Male,Guess,1995-05-29,2007-09-23,8.33,7.0,5840.0,vubsgjmi@gmail.com,NJkVtBYv
21,zZKinhoZz,6951407,10,65,8,22,73.30,Male,"Camaragibe, Pernambuco",2000-04-04,2018-02-03,6.21,4.0,4455.0,tfzhvldi@gmail.com,cvtktlTV
22,glittermilk,502600,15,35,6,70,17.20,Female,ａｕｓｔｒｉａ。,1994-04-13,2011-06-23,7.91,1.0,1004.0,zyrojmih@gmail.com,zVCrIAKi
23,fluffylonewolf,1537662,6,121,12,175,27.63,Female,Canada,1989-01-01,2012-09-24,8.40,0.0,1602.0,gvhagyiy@gmail.com,NTALBveS
24,Lithuelle,2637160,3,148,1,110,118.16,Female,"Rhineland-Palatinate, Germany",1985-10-19,2013-05-29,7.14,282.0,7447.0,thomcsvy@gmail.com,mhovcCvk
25,scootarski,19540,4,269,8,207,62.81,Male,Philadelphia PA,1984-10-12,2007-10-31,7.39,0.0,3606.0,lpshiyoq@gmail.com,FZpOmrQT
26,Yukia-Kontan,60452,1,13,0,7,4.15,Male,"Carbonear, Newfoundland",1990-12-19,2008-05-14,7.38,4.0,222.0,jatynrxm@gmail.com,rFvQzsOo
27,Akihara,82965,17,623,12,27,254.20,Female,Romania,1994-08-11,2008-08-05,7.46,20.0,15228.0,jazftjeq@gmail.com,YvmQEchI
28,Tomoki-sama,1933207,10,348,28,172,103.18,Male,"SC, Brasil",1996-06-01,2012-12-22,8.48,8.0,6255.0,yzlyyqll@gmail.com,uICFyyAl
29,Sakurei,158249,4,621,8,64,284.76,Female,"Vienna, Austria",2003-02-10,2009-03-11,5.15,66.0,17174.0,hezluftx@gmail.com,hCRNhoNY
30,raickos,363956,25,172,0,0,74.55,Male,"Parana, Brasil",1989-08-17,2010-08-01,9.45,3.0,4367.0,sddedlei@gmail.com,tTyaZriC
31,Spike,4918731,5,353,2,54,99.66,Female,Salisbury NC,1994-04-16,2015-10-05,7.27,10.0,6003.0,zdavkfbl@gmail.com,ZBbvUtpv
32,Perfection_Freak,183037,15,389,27,4,131.97,Female,"Kemerovo, Russia",1992-01-20,2009-05-16,7.25,20.0,8141.0,wvbkjofk@gmail.com,ijsiWjHe
33,AAA,38502,1,84,2,2,23.89,Male,Starlight Breaker,1991-05-16,2008-02-20,7.52,4.0,1431.0,nsehenfa@gmail.com,EVOgxUbx
34,K_P,6553595,32,419,3,122,181.52,Male,India,1998-02-06,2017-09-13,9.05,140.0,11019.0,jnodijbp@gmail.com,exScdEij
35,LyannaStark,167813,14,39,14,87,29.12,Female,"Sofia, Bulgaria",1989-09-25,2009-04-07,7.70,10.0,1771.0,ujfttjuf@gmail.com,ezntNpma
36,xXsim00Xx,3791942,4,294,2,60,63.33,Male,New South Wales,1998-02-01,2014-05-22,7.72,4.0,3860.0,xknjbqls@gmail.com,IvCKWInh
37,Kyousuke,4663749,1,25,22,17,10.20,Male,"Buenos Aires, Argentina",2001-01-13,2015-06-08,6.98,0.0,637.0,icigqsdk@gmail.com,OdbjSPXQ
38,magedgamed,4511508,14,1166,30,140,285.85,Male,"Cairo, Egypt",1997-02-12,2015-03-21,7.48,211.0,17031.0,jdwjdart@gmail.com,lqscJgUF
39,edwardf,120129,0,52,1,6,35.31,Male,"Pelotas,Brasil",1993-02-07,2008-12-03,5.96,0.0,2166.0,evdiaqaz@gmail.com,tlsCPuDc
40,diordiah,936,21,171,80,5,61.38,Female,"Chester, California",1985-09-02,2006-10-10,6.03,0.0,3725.0,tmeuydst@gmail.com,mJBdpyJv
41,ShinyShinigami,4420328,45,443,0,1450,160.69,Male,Justinside a Reality Marble,2000-10-05,2015-01-15,6.88,7.0,9793.0,jrasnmru@gmail.com,CkUOmABi
42,KawaiiChiyo,441585,3,5,0,1,1.74,Female,"Philippines, Bulacan",1999-07-04,2011-01-29,9.50,0.0,108.0,dyuuzive@gmail.com,JumZKsIH
43,SenpajBiju,5285184,18,166,8,41,95.75,Male,United Kingdom,2000-07-16,2016-03-24,8.35,0.0,5757.0,koebdwmy@gmail.com,ChTyTLYn
44,anime_fan_800,29394,18,121,1,300,86.15,Male,Kansas,1985-01-01,2008-01-03,7.86,155.0,4784.0,wtjcsnto@gmail.com,cbtEZhRa
45,WhatsUpWitches,5158639,6,63,0,20,58.54,Male,"Atlanta, Georgia",1996-05-01,2016-01-26,8.16,4.0,3488.0,vfdqhnbz@gmail.com,UqSfOeYm
46,Wizzaroo,317747,3,74,60,70,64.92,Male,Portugal,1996-01-02,2010-04-17,7.57,4.0,3866.0,gfijziom@gmail.com,xOQrodZx
47,pim,57780,7,417,14,84,119.29,Female,what do you want,1930-10-08,2008-05-03,6.45,37.0,7068.0,pdfgqdiz@gmail.com,ahXxYYDr
48,Seishuku,109555,16,177,32,33,88.72,Male,"Malbork, Poland",1988-04-12,2008-10-29,7.36,0.0,5288.0,mutauomp@gmail.com,dsLXMHCL
49,SynysterKobra,171690,2,11,0,52,7.10,Male,California,1993-04-20,2009-04-16,9.15,3.0,407.0,tcmzuovu@gmail.com,jUcWwfQc